### ISSUE TITLE
awesome-xamarin

### ISSUE THREAD

**Issue by benoitjadinon** [MarcBruins/awesome-xamarin#32]
hi, @MarcBruins, 
I like your initiative, but did you know you could have pull requested anything to https://github.com/benoitjadinon/awesome-xamarin ?
my original idea was to mostly list libraries that target more than one platform, but I like your idea of supported OS icons better.
that being said, as a cross-platform developer, I don't like duplication ;) do you think we can we merge our repos somehow ? 
mine is listed on https://github.com/sindresorhus/awesome but I guess you don't want to lose your stars, nor do I, and duplication is really too bad, any idea?
thx

**Comment by MarcBruins** [comment]
Hello @benoitjadinon. I found it later that you already also had a "Awesome-xamarin". Furthermore i wanted to make a extensible list with not only libraries or sdks but also bindings and ports and give them an indication about which platform(s) they support. Are you on slack? Lets talk about it in there? (my slack name in the xamarin channel is MarcBruins)
