### ISSUE TITLE
Single awesome-xamarin repository

### ISSUE THREAD

**Issue by yauhenipakala** [MarcBruins/awesome-xamarin#37]
Hi @MarcBruins and @benoitjadinon, can your think about merging two of the same repositories:

https://github.com/MarcBruins/awesome-xamarin
https://github.com/benoitjadinon/awesome-xamarin

**Comment by benoitjadinon** [comment]
#32

**Comment by benoitjadinon** [comment]
finally done, invited @MarcBruins : https://github.com/XamSome/awesome-xamarin

**Comment by yauhenipakala** [comment]
Awesome, thanks!

**Comment by MarcBruins** [comment]
Nice work @benoitjadinon i've just joined!
