### ISSUE TITLE
The Syncfusion chart supports macOS now !!!

### ISSUE THREAD

**Issue by prabakaranr** [MarcBruins/awesome-xamarin#48]
Thank you for this great documentation :).

Could you please make the following changes in the content of Syncfusion chart?

1. Now chart supports macOS platform as well along with iOS, Android and UWP. So, it will be good if it is mentioned in your document as it helps the users those who are looking for the chart component in Xamarin.Forms that supports macOS.
2. Syncfusion chart now supports more than 25 chart types.

Note: I work for Syncfusion.

**Comment by MarcBruins** [comment]
Please make a PR
